name: compassx_example
description: "Demonstrates how to use the compassx plugin."
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  compassx:
    path: ../
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  device_info_plus: ^10.0.1
flutter:
  uses-material-design: true
