name: compassx
description: "Compass plugin for Flutter."
version: 0.0.1
homepage: https://pub.dev/packages/compassx
repository: https://github.com/natsuk4ze/compassx
documentation: https://github.com/natsuk4ze/compassx/wiki
funding: 
 - https://github.com/sponsors/natsuk4ze

topics:
 - compass
 - sensor
 - heading
 - north
 - calibration


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: studio.midoridesign.compassx
        pluginClass: CompassXPlugin
      ios:
        pluginClass: CompassXPlugin